version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    hostname: haproxy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
      - certificates:/usr/local/etc/haproxy/certificates

  certbot:
    image: shoplcj/certbot:latest
    build: ./certbot
    container_name: certbot
    hostname: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do . /etc/scripts/renew-certificates.sh ; sleep 12h & wait $${!}; done;'"
    restart: always
    networks:
      - haproxy
    volumes:
      - certificates:/etc/certificates

  mongo:
    image: mongo:4.4.5
    container_name: mongo
    hostname: mongo
    restart: always
    networks:
      - mongo
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  shop:
    image: shoplcj/shop:latest
    build: ./shop
    container_name: shop
    hostname: shop
    restart: always
    networks:
      - haproxy
      - api
    environment:
      - VITE_LOCAL_API_URL
      - VITE_REMOTE_API_URL

  api:
    image: shoplcj/api:latest
    build: ./api
    container_name: api
    hostname: api
    restart: always
    networks:
      - haproxy
      - api
      - mongo
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/shoplcj?authSource=admin&appName=shoplcj
      - APP_PORT=5000
      - API_SECRET_JWT


volumes:
  certificates:
    external: true
    name: certificates
  mongo:
    external: true
    name: mongo


networks:
  haproxy:
    external: false
    name: haproxy
  mongo:
    external: false
    name: mongo
  api:
    external: false
    name: api
