version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    hostname: haproxy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
      - certificates:/usr/local/etc/haproxy/certificates
    depends_on:
      - shop
      - api
      - admin

  certbot:
    image: shoplcj/certbot:latest
    build: ./certbot
    container_name: certbot
    hostname: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do . /etc/scripts/renew-certificates.sh ; sleep 12h & wait $${!}; done;'"
    restart: always
    networks:
      - haproxy
    volumes:
      - certificates:/etc/certificates
    depends_on:
      - haproxy

  mongo:
    image: mongo:4.4.5
    container_name: mongo
    hostname: mongo
    restart: always
    networks:
      - mongo
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  shop:
    image: shoplcj/shop:latest
    build: ./shop
    container_name: shop
    hostname: shop
    restart: always
    networks:
      - haproxy
      - api

  admin:
    image: shoplcj/admin:latest
    build: ./admin
    container_name: admin
    hostname: admin
    restart: always
    networks:
      - haproxy
      - api

  api:
    image: shoplcj/api:latest
    build: ./api
    container_name: api
    hostname: api
    restart: always
    networks:
      - haproxy
      - api
      - mongo
    volumes:
      - apibackups:/usr/src/app/backups
      - apistorage:/usr/src/app/storage
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/shoplcj?authSource=admin&appName=shoplcj
      - APP_PORT=5000
      - API_SECRET_JWT
      - APP_DOMAIN
      - SENDGRID_API_KEY
    depends_on:
      - mongo


volumes:
  certificates:
    external: true
    name: certificates
  mongo:
    external: true
    name: mongo
  apibackups:
    external: true
    name: apibackups
  apistorage:
    external: true
    name: apistorage


networks:
  haproxy:
    external: false
    name: haproxy
  mongo:
    external: false
    name: mongo
  api:
    external: false
    name: api
